/*
 *Guilherme Cabral - 262546
 *Matheus Kleinubing - 262551
 *O programa não faz listagens e não efetua operações com arquivos.
 */
package InterfacesGraficas;

import ClassesAtributo.Biblioteca;

/**
 *
 * @author Guilherme Cabral
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        butCadastro = new javax.swing.JButton();
        butEmprestimo = new javax.swing.JButton();
        butConsultaLocal = new javax.swing.JButton();
        butDevolucao = new javax.swing.JButton();
        butPagamento = new javax.swing.JButton();
        butPesquisa = new javax.swing.JButton();
        butListagens = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        imgLogoUfrgs = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        butCadastro.setText("Cadastro");
        butCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCadastroActionPerformed(evt);
            }
        });

        butEmprestimo.setText("Empréstimo");
        butEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEmprestimoActionPerformed(evt);
            }
        });

        butConsultaLocal.setText("Consulta Local");
        butConsultaLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butConsultaLocalActionPerformed(evt);
            }
        });

        butDevolucao.setText("Devolução");
        butDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDevolucaoActionPerformed(evt);
            }
        });

        butPagamento.setText("Pagamento");
        butPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPagamentoActionPerformed(evt);
            }
        });

        butPesquisa.setText("Pesquisa");
        butPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPesquisaActionPerformed(evt);
            }
        });

        butListagens.setText("Listagens");
        butListagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butListagensActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butEmprestimo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butPagamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butConsultaLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butListagens, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(70, 70, 70))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {butCadastro, butConsultaLocal, butDevolucao, butEmprestimo, butListagens, butPagamento, butPesquisa});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(butCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butEmprestimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butConsultaLocal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butDevolucao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butPagamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butListagens)
                .addGap(50, 50, 50))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(172, 100));

        imgLogoUfrgs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo Ufrgs.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(imgLogoUfrgs)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(imgLogoUfrgs)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void butCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCadastroActionPerformed
        // TODO add your handling code here:      
        MenuCadastro menuCad = new MenuCadastro();
        menuCad.setVisible(true);
    }//GEN-LAST:event_butCadastroActionPerformed

    private void butEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEmprestimoActionPerformed
        // TODO add your handling code here:
        MenuEmprestimo menuEmp = new MenuEmprestimo();
        menuEmp.setVisible(true);
        menuEmp.setTesteConf(1);
    }//GEN-LAST:event_butEmprestimoActionPerformed

    private void butConsultaLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butConsultaLocalActionPerformed
        // TODO add your handling code here:
        // Reaproveitando o menu de empréstimo.
        MenuEmprestimo menuConLoc = new MenuEmprestimo();
        menuConLoc.setVisible(true);
        menuConLoc.setTitle("Consulta Local");
        menuConLoc.setTesteConf(2);
    }//GEN-LAST:event_butConsultaLocalActionPerformed

    private void butDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDevolucaoActionPerformed
        // TODO add your handling code here:
        // Reaproveitando o menu de empréstimo.
        MenuEmprestimo menuDev = new MenuEmprestimo();
        menuDev.setVisible(true);
        menuDev.setTitle("Devolução");
        menuDev.setButDev();
        menuDev.setTesteConf(3);
    }//GEN-LAST:event_butDevolucaoActionPerformed

    private void butPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPagamentoActionPerformed
        // Abre uma janela de pesquisa de usuário.
        MenuPesquisaIdUser menuID = new MenuPesquisaIdUser();
        menuID.setVisible(true);
        menuID.setTitle("Pesquisa Pagamento");
        menuID.setActionButPesquisar("Pagamento");
    }//GEN-LAST:event_butPagamentoActionPerformed

    private void butPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPesquisaActionPerformed
        // TODO add your handling code here:
        MenuPesquisa menuPesq = new MenuPesquisa();
        menuPesq.setVisible(true);
    }//GEN-LAST:event_butPesquisaActionPerformed

    private void butListagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butListagensActionPerformed
        // TODO add your handling code here:
        MenuListagens menuList = new MenuListagens();
        menuList.setVisible(true);
    }//GEN-LAST:event_butListagensActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCadastro;
    private javax.swing.JButton butConsultaLocal;
    private javax.swing.JButton butDevolucao;
    private javax.swing.JButton butEmprestimo;
    private javax.swing.JButton butListagens;
    private javax.swing.JButton butPagamento;
    private javax.swing.JButton butPesquisa;
    private javax.swing.JLabel imgLogoUfrgs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
