/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesGraficas;

/**
 *
 * @author Guilherme Cabral
 */
public class MenuCadastro extends javax.swing.JFrame {

    /**
     * Creates new form MenuCadastro
     */
    public MenuCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        butCadUsuario = new javax.swing.JButton();
        butAltUsuario = new javax.swing.JButton();
        butDelUsuario = new javax.swing.JButton();
        butCadDocumento = new javax.swing.JButton();
        butAltDocumento = new javax.swing.JButton();
        butDelDocumento = new javax.swing.JButton();

        setTitle("Cadastro");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        butCadUsuario.setText("Cadastro Usuário");
        butCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCadUsuarioActionPerformed(evt);
            }
        });

        butAltUsuario.setText("Alterar Usuário");
        butAltUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAltUsuarioActionPerformed(evt);
            }
        });

        butDelUsuario.setText("Deletar Usuário");
        butDelUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDelUsuarioActionPerformed(evt);
            }
        });

        butCadDocumento.setText("Cadastro Documento");
        butCadDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCadDocumentoActionPerformed(evt);
            }
        });

        butAltDocumento.setText("Alterar Documento");
        butAltDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAltDocumentoActionPerformed(evt);
            }
        });

        butDelDocumento.setText("Deletar Documento");
        butDelDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDelDocumentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(butCadUsuario)
                        .addGap(30, 30, 30)
                        .addComponent(butCadDocumento))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(butAltUsuario)
                        .addGap(30, 30, 30)
                        .addComponent(butAltDocumento))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(butDelUsuario)
                        .addGap(30, 30, 30)
                        .addComponent(butDelDocumento)))
                .addGap(70, 70, 70))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {butAltDocumento, butAltUsuario, butCadDocumento, butCadUsuario, butDelDocumento, butDelUsuario});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butCadUsuario)
                    .addComponent(butCadDocumento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butAltUsuario)
                    .addComponent(butAltDocumento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butDelUsuario)
                    .addComponent(butDelDocumento))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCadUsuarioActionPerformed
        // TODO add your handling code here:
        MenuCadastroUsuario menuCadUser = new MenuCadastroUsuario();
        menuCadUser.setVisible(true);
        dispose();
    }//GEN-LAST:event_butCadUsuarioActionPerformed

    private void butAltUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAltUsuarioActionPerformed
        // Abre uma caixa de busca de usuário.
        MenuPesquisaIdUser menuID = new MenuPesquisaIdUser();
        menuID.setVisible(true);
        menuID.setActionButPesquisar("Alt User");
        dispose();
    }//GEN-LAST:event_butAltUsuarioActionPerformed

    private void butDelUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDelUsuarioActionPerformed
        // Abre uma caixa de busca de usuário.
        MenuPesquisaIdUser menuID = new MenuPesquisaIdUser();
        menuID.setVisible(true);
        menuID.setTitle("Pesquisa Deletar");
        menuID.setActionButPesquisar("Del User");
        dispose();
    }//GEN-LAST:event_butDelUsuarioActionPerformed

    private void butCadDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCadDocumentoActionPerformed
        // Abre uma caixa de cadastro de documento.
        MenuCadastroDocumento menuCadDoc = new MenuCadastroDocumento();
        menuCadDoc.setVisible(true);
        dispose();
    }//GEN-LAST:event_butCadDocumentoActionPerformed

    private void butAltDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAltDocumentoActionPerformed
        // TAbre uma caixa de busca de documento.
        MenuPesquisaIdUser menuID = new MenuPesquisaIdUser();
        menuID.setVisible(true);
        menuID.setLabelTextDoc();
        menuID.setActionButPesquisar("Alt Doc");
        menuID.pack();
        menuID.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_butAltDocumentoActionPerformed

    private void butDelDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDelDocumentoActionPerformed
        // Abre uma caixa de busca de documento.
        MenuPesquisaIdUser menuID = new MenuPesquisaIdUser();
        menuID.setVisible(true);
        menuID.setLabelTextDoc();
        menuID.setTitle("Pesquisa Deletar");
        menuID.setActionButPesquisar("Del Doc");
        menuID.pack();
        menuID.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_butDelDocumentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAltDocumento;
    private javax.swing.JButton butAltUsuario;
    private javax.swing.JButton butCadDocumento;
    private javax.swing.JButton butCadUsuario;
    private javax.swing.JButton butDelDocumento;
    private javax.swing.JButton butDelUsuario;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
