/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesGraficas;

import ClassesAtributo.Biblioteca;

/**
 *
 * @author Guilherme Cabral
 */
public class MenuDadosDoc extends javax.swing.JFrame {

    /**
     * Creates new form MenuDadosDoc
     */
    public MenuDadosDoc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labTitulo = new javax.swing.JLabel();
        labID = new javax.swing.JLabel();
        labAutor = new javax.swing.JLabel();
        labAssunto = new javax.swing.JLabel();
        labAno = new javax.swing.JLabel();
        labPaginas = new javax.swing.JLabel();
        labQuantia = new javax.swing.JLabel();
        labTipo = new javax.swing.JLabel();
        labTitulo2 = new javax.swing.JLabel();
        labID2 = new javax.swing.JLabel();
        labAutor2 = new javax.swing.JLabel();
        labAssunto2 = new javax.swing.JLabel();
        labAno2 = new javax.swing.JLabel();
        labPaginas2 = new javax.swing.JLabel();
        labQuantia2 = new javax.swing.JLabel();
        labTipo2 = new javax.swing.JLabel();
        butDeletar = new javax.swing.JButton();
        butCandelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Deletar");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labTitulo.setText("Título:");

        labID.setText("ID:");

        labAutor.setText("Autor:");

        labAssunto.setText("Assunto:");

        labAno.setText("Ano:");

        labPaginas.setText("Páginas:");

        labQuantia.setText("Quantia:");

        labTipo.setText("Tipo:");

        butDeletar.setText("Deletar");
        butDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDeletarActionPerformed(evt);
            }
        });

        butCandelar.setText("Cancelar");
        butCandelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCandelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labTitulo)
                    .addComponent(labID)
                    .addComponent(labAutor)
                    .addComponent(labAssunto)
                    .addComponent(labAno)
                    .addComponent(labPaginas)
                    .addComponent(labQuantia)
                    .addComponent(labTipo))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labTipo2)
                    .addComponent(labPaginas2)
                    .addComponent(labAno2)
                    .addComponent(labAssunto2)
                    .addComponent(labAutor2)
                    .addComponent(labID2)
                    .addComponent(labTitulo2)
                    .addComponent(labQuantia2))
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butDeletar)
                .addGap(30, 30, 30)
                .addComponent(butCandelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTitulo)
                    .addComponent(labTitulo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labID)
                    .addComponent(labID2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labAutor)
                    .addComponent(labAutor2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labAssunto)
                    .addComponent(labAssunto2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labAno)
                    .addComponent(labAno2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labPaginas)
                    .addComponent(labPaginas2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labQuantia)
                    .addComponent(labQuantia2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTipo)
                    .addComponent(labTipo2))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butDeletar)
                    .addComponent(butCandelar))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDeletarActionPerformed
        if (butDeletar.getText() == "Deletar")
        {System.out.println("del");
        Biblioteca.removeDoc(labID2.getText());
        }
        dispose();
    }//GEN-LAST:event_butDeletarActionPerformed

    private void butCandelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCandelarActionPerformed
        dispose();
    }//GEN-LAST:event_butCandelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDadosDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDadosDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDadosDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDadosDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDadosDoc().setVisible(true);
            }
        });
    }
    
    //Setter
    public void setTextLabTitulo(String s)
    {
        labTitulo2.setText(s);
    }
    public void setTextLabID(String s)
    {
        labID2.setText(s);
    }
    public void setTextLabAutor(String s)
    {
        labAutor2.setText(s);
    }
    public void setTextLabAssunto(String s)
    {
        labAssunto2.setText(s);
    }
    public void setTextLabAno(String s)
    {
        labAno2.setText(s);
    }
    public void setTextLabPaginas(String s)
    {
        labPaginas2.setText(s);
    }
    public void setTextLabQuantia(String s)
    {
        labQuantia2.setText(s);
    }
    public void setTextLabTipo(String s)
    {
        labTipo2.setText(s);
    }
    public void setTextButDeletar(String s)
    {
        butDeletar.setText(s);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCandelar;
    private javax.swing.JButton butDeletar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labAno;
    private javax.swing.JLabel labAno2;
    private javax.swing.JLabel labAssunto;
    private javax.swing.JLabel labAssunto2;
    private javax.swing.JLabel labAutor;
    private javax.swing.JLabel labAutor2;
    private javax.swing.JLabel labID;
    private javax.swing.JLabel labID2;
    private javax.swing.JLabel labPaginas;
    private javax.swing.JLabel labPaginas2;
    private javax.swing.JLabel labQuantia;
    private javax.swing.JLabel labQuantia2;
    private javax.swing.JLabel labTipo;
    private javax.swing.JLabel labTipo2;
    private javax.swing.JLabel labTitulo;
    private javax.swing.JLabel labTitulo2;
    // End of variables declaration//GEN-END:variables
}
